[project]
name = "bake-rows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "langdetect>=1.0.9",
    "numpy>=2.2.5",
    "polars>=1.27.1",
    "regex>=2024.11.6",
    "sentence-transformers>=4.1.0",
]
